spring:
  application:
    name: produce-movies

  datasource:
    url: ${SPRING_DATASOURCE_URL:${DATASOURCE_URL}}
    username: ${SPRING_DATASOURCE_USERNAME:${DATASOURCE_USER}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DATASOURCE_PASSWORD}}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

front-end:
  url: ${FRONT_END_URL}

app:
  jwt:
    secret: ${APP_JWT_SECRETE}
    expirationMs: 86400000
