spring:
  application:
    name: produce-movies
  datasource:
    url: ${DATASOURCE_URL}
    username:  ${DATASOURCE_USER}
    password:  ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
front-end:
  url: ${FRONT_END_URL}}

app:
  jwt:
    secret: ${APP_JWT_SECRETE}
    expirationMs: 86400000

omdb:
  api-key: 4c2221ce
  base-url: https://www.omdbapi.com/
